In [331]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
plt.style.use('dark_background')

data = pd.read_csv('../Dataset/Social_Network_Ads.csv')
data

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

---
**With gender**

In [332]:
X = data.iloc[:,1:-1]
y = data.iloc[:,-1]
X

     Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [333]:
le = LabelEncoder()
ss = StandardScaler()
X.iloc[:,[0]] = le.fit_transform(X.iloc[:,[0]])
X.iloc[:,1:] = ss.fit_transform(X.iloc[:,1:])

c:\Users\Dell\miniconda3\envs\AIML\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_31140\77807255.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.78179743 -0.25358736 -1.11320552 -1.01769239 -1.78179743 -1.01769239
 -1.01769239 -0.54012675 -1.20871865 -0.25358736 -1.11320552 -1.11320552
 -1.6862843  -0.54012675 -1.87731056 -0.82666613  0.89257019  0.70154394
  0.79705706  0.98808332  0.70154394  0.89257019  0.98808332  0.70154394
  0.79705706  0.89257019  1.08359645  0.89257019 -0.82666613 -0.63563988
 -0.63563988 -1.01769239 -1.59077117 -0.92217926 -1.01769239 -0.25358736
 -0.44461362 -0.73115301 -1.11320552 -1.01769239 -1.01769239 -0.44461362
 -0.25358736 -0.73115301 -0.92217926 -1.39974491 -1.20871865 -1.01769239
 -0.73115301 -0.63563988 -1.30423178 -1.87731056 -0.82666613 -0.25358736
 -1.01769239 -1.30423178 -1.39974491 -0.92217926 -1.49525804 -0.54012675
 -1.01769239 -1.20871865 -1.39974491 -0.54012675  2.03872775 -1.30423178
 -1.30423178 -1.39974491 -1.49525804 -0.63563988 -1.20871865 -1.30423178
 -1.6862843  -0.44461362 -0.54012675 -0.34910049 -1.87731056 -1.49525804
 -0.92217926 -1.11320552 -0.73115301  0.12846516 -1.6862843  -0.25358736
 -0.73115301 -0.63563988 -1.30423178 -0.92217926 -1.11320552 -0.25358736
 -1.49525804 -0.73115301 -1.11320552 -0.82666613 -0.82666613 -0.25358736
 -0.25358736 -0.92217926 -0.25358736 -0.92217926 -1.01769239 -0.92217926
 -0.54012675 -0.44461362 -1.78179743 -1.59077117 -1.11320552 -1.01769239
 -1.11320552  0.03295203  0.12846516 -0.0625611   0.03295203 -0.0625611
  0.41500455  0.22397829 -0.25358736 -0.15807423  0.22397829  0.31949142
 -0.15807423 -0.0625611   0.22397829 -0.25358736  0.31949142  0.12846516
  0.41500455 -1.11320552 -0.73115301 -1.11320552 -0.63563988 -0.44461362
 -0.73115301 -1.59077117 -0.92217926 -1.39974491 -1.6862843  -0.73115301
 -0.92217926 -1.78179743 -1.78179743 -1.87731056 -0.25358736 -0.73115301
 -0.34910049 -1.30423178 -1.01769239  0.31949142 -0.82666613 -1.6862843
 -1.11320552  0.31949142 -0.63563988 -0.15807423  0.22397829 -0.63563988
  0.79705706 -0.82666613 -1.11320552 -0.54012675 -0.54012675 -1.20871865
 -0.0625611  -0.25358736 -0.44461362 -1.87731056 -1.49525804 -0.25358736
 -0.82666613 -0.82666613 -1.59077117 -0.34910049 -1.11320552 -0.34910049
 -0.34910049 -1.39974491 -0.25358736 -1.20871865 -1.30423178 -0.63563988
 -1.11320552 -0.63563988 -0.54012675 -0.44461362 -0.44461362 -0.63563988
 -1.6862843  -0.44461362 -0.25358736 -0.92217926 -1.30423178 -1.78179743
 -0.82666613 -1.78179743 -0.92217926 -0.34910049 -0.73115301 -1.6862843
 -1.11320552 -0.25358736 -0.25358736  1.08359645  0.12846516  0.31949142
  1.94321462  0.89257019  1.65667523  1.37013584  0.22397829  0.79705706
  0.98808332  1.37013584  2.03872775 -0.25358736  0.89257019  2.13424088
  1.08359645  0.22397829  0.79705706  2.03872775  0.31949142 -0.25358736
 -0.0625611   2.13424088 -0.25358736 -0.0625611  -0.15807423  1.75218836
  0.22397829  0.41500455 -0.25358736  0.12846516  0.22397829  1.08359645
  0.03295203  0.79705706  0.22397829 -0.0625611   0.79705706  1.46564897
  0.41500455  0.03295203  1.17910958  1.75218836  0.31949142  1.27462271
 -0.25358736  1.84770149  0.31949142 -0.25358736  0.60603081 -0.0625611
  0.98808332 -0.0625611   1.17910958  1.37013584  0.31949142  0.22397829
  1.94321462  0.70154394 -0.25358736 -0.15807423  1.65667523 -0.25358736
  0.98808332  0.41500455  0.22397829 -0.0625611   0.89257019  0.22397829
  0.51051768  2.03872775  2.13424088  0.12846516  1.84770149  1.84770149
  0.03295203  1.08359645  1.37013584  1.17910958  2.03872775 -0.25358736
 -0.0625611   1.37013584  0.98808332 -0.0625611  -0.0625611   0.98808332
  0.31949142 -0.0625611   0.12846516  1.08359645  1.65667523 -0.0625611
 -0.25358736 -0.15807423  0.41500455  0.51051768  0.70154394  0.79705706
  1.94321462  0.98808332 -0.0625611  -0.0625611   0.22397829  0.41500455
  1.27462271  0.89257019 -0.15807423  0.03295203  0.41500455  0.12846516
  0.03295203  1.08359645  0.12846516  0.12846516  1.5611621  -0.25358736
  0.70154394 -0.15807423  1.37013584  1.46564897  0.31949142  0.98808332
  0.98808332  0.31949142  0.31949142  0.41500455 -0.15807423  0.89257019
  0.03295203  0.98808332  0.41500455  0.22397829  1.84770149 -0.15807423
  1.94321462 -0.25358736  0.03295203  0.12846516  1.46564897 -0.25358736
  0.03295203  0.89257019  0.89257019  0.31949142  1.46564897  1.5611621
  0.12846516  0.03295203  0.03295203 -0.0625611   0.41500455 -0.0625611
 -0.15807423  2.13424088  1.5611621   0.31949142  0.22397829  0.41500455
  0.51051768  1.46564897  0.89257019  0.41500455  0.41500455  2.03872775
  1.94321462  0.79705706  0.03295203  1.5611621   2.13424088  2.13424088
  0.12846516  2.03872775 -0.0625611   0.79705706  0.79705706  0.41500455
  0.31949142  1.94321462  0.41500455  0.98808332  0.60603081  1.08359645
  1.84770149  1.75218836  1.08359645  0.12846516  0.89257019  0.98808332
  0.98808332  0.89257019  0.70154394  2.13424088  0.12846516  0.79705706
  1.27462271  1.17910958 -0.15807423  1.08359645]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X.iloc[:,1:] = ss.fit_transform(X.iloc[:,1:])
C:\Users\Dell\AppData\Local\Temp\ipykernel_31140\77807255.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.49004624 -1.46068138 -0.78528968 -0.37418169  0.18375059 -0.34481683
  0.41866944  2.35674998 -1.07893824 -0.13926283  0.30121002 -0.52100597
  0.47739916 -1.51941109  0.35993973  0.30121002 -1.3138571  -1.28449224
 -1.22576253 -1.19639767 -1.40195167 -0.60910054 -0.84401939 -1.40195167
 -1.37258681 -1.46068138 -1.22576253 -1.16703281 -0.78528968 -1.51941109
  0.12502088  1.97500684 -1.5781408  -0.75592482  0.59485858 -1.25512738
 -1.22576253 -0.60910054  0.06629116 -1.13766796 -1.54877595 -0.55037082
  1.123426   -1.60750566  0.41866944 -1.46068138  0.27184516 -0.46227625
  1.91627713  0.56549373 -1.1083031  -0.75592482  0.38930459 -1.37258681
 -0.34481683 -0.4329114  -0.63846539  0.27184516 -1.51941109  1.38770971
 -1.46068138  0.50676401 -0.10989798  1.47580428  0.38930459 -0.34481683
 -1.49004624  0.35993973 -0.19799255 -0.05116826  0.30121002 -1.25512738
 -1.37258681  1.27025028 -1.51941109  1.24088543 -0.52100597 -1.25512738
  0.50676401 -1.54877595  0.30121002 -0.81465453 -0.60910054  0.53612887
 -0.2273574   1.41707457 -0.4329114   0.4480343   0.33057487 -0.57973568
  0.33057487  1.35834485 -1.60750566 -1.22576253  0.38930459 -0.75592482
 -1.3138571   1.56389885  0.09565602 -0.96147882  0.53612887 -0.31545197
  0.47739916  2.32738512 -1.43131652  0.06629116 -1.02020853  0.56549373
  0.47739916  0.30121002  0.03692631  0.03692631 -0.25672226 -0.4329114
  0.30121002 -0.37418169  0.15438573 -0.52100597 -0.31545197 -0.31545197
  0.15438573  0.06629116  0.15438573 -0.49164111 -0.55037082 -0.25672226
 -0.13926283 -1.1083031  -1.54877595  0.41866944 -0.34481683 -1.13766796
  0.50676401 -0.05116826 -0.4329114  -0.19799255  0.35993973  1.09406114
 -0.31545197 -1.3138571   0.4480343  -0.05116826 -0.31545197  0.56549373
 -1.3138571   0.56549373  0.77104772 -1.16703281 -0.25672226  0.12502088
 -1.60750566 -0.72655996  0.18375059 -0.57973568 -0.66783025 -1.60750566
 -0.31545197  0.15438573 -1.16703281  1.91627713  0.88850715  0.59485858
 -1.07893824 -0.93211396 -0.02180341  0.47739916 -0.4329114   0.03692631
  2.29802026 -0.66783025  0.53612887  1.32898     1.41707457 -0.78528968
  0.06629116 -1.22576253 -0.66783025 -1.40195167 -1.37258681 -1.04957339
 -1.5781408   0.03692631  1.38770971 -0.78528968 -0.28608712 -0.10989798
  0.35993973 -0.84401939  0.06629116 -1.1083031   0.41866944 -1.28449224
 -0.78528968  0.00756145  0.56549373 -0.78528968  0.27184516 -0.99084367
  0.30121002 -1.40195167 -0.9027491   0.12502088  1.88691227  0.03692631
  0.917872   -0.66783025  1.76945285  1.29961514  2.12183112 -1.40195167
  0.77104772  2.35674998 -0.81465453 -0.34481683 -0.78528968  1.123426
 -0.13926283  0.2424803   0.77104772  2.15119598  0.30121002  0.62422344
  2.18056084  0.94723686 -0.28608712 -0.49164111  1.65199342  1.85754742
  0.06629116  0.30121002  2.26865541 -0.81465453  1.09406114  0.47739916
  1.24088543  0.27184516 -0.37418169  0.30121002  0.35993973  2.15119598
  2.32738512 -0.31545197  0.53612887  1.00596657  0.06629116  2.23929055
 -0.57973568  1.53453399 -0.52100597  0.80041258 -0.9027491  -0.52100597
  1.88691227  2.23929055 -0.75592482  0.59485858  0.06629116 -0.37418169
  0.74168287  1.7988177   0.21311545  2.18056084  1.62262856  0.06629116
  0.59485858  1.123426    0.15438573  0.12502088  2.18056084 -0.25672226
  1.85754742  0.18375059 -0.81465453  1.06469629 -1.28449224  0.12502088
  0.03692631  0.53612887 -0.93211396 -0.99084367  0.53612887 -0.25672226
  0.00756145 -1.43131652  2.09246627  0.68295315 -0.2273574   2.0043717
  0.27184516  0.2424803   1.88691227  0.56549373 -0.9027491   0.21311545
 -0.37418169 -0.19799255  0.09565602  1.24088543  0.27184516  1.38770971
 -0.93211396  0.12502088  1.97500684  0.27184516 -0.28608712 -0.46227625
  1.88691227  1.27025028  1.62262856 -0.57973568  0.00756145  0.77104772
 -0.57973568  2.09246627  0.27184516  0.15438573  1.00596657 -0.4329114
 -1.1083031  -0.28608712  2.0043717   0.35993973 -0.52100597 -1.16703281
  1.7988177  -0.28608712  0.06629116  0.15438573  1.41707457  1.09406114
 -0.55037082  1.44643942 -0.13926283 -0.13926283 -0.28608712 -0.46227625
  2.18056084  0.27184516 -0.4329114   1.53453399  1.00596657  0.15438573
 -0.13926283 -0.55037082  1.03533143 -0.19799255  0.06629116  1.123426
  0.21311545 -0.25672226  1.27025028  0.15438573  0.59485858 -0.37418169
  0.85914229 -1.04957339  0.00756145  0.06629116  0.03692631 -0.46227625
  1.74008799 -1.04957339 -0.57973568  0.27184516  1.00596657 -1.19639767
 -0.66783025  0.53612887  0.03692631 -1.28449224 -0.69719511  0.38930459
  0.09565602  1.76945285  0.30121002 -1.1083031   0.12502088 -0.49164111
  0.50676401 -1.37258681 -0.16862769 -1.07893824  2.03373655 -1.22576253
 -1.07893824 -0.28608712 -0.9027491   0.03692631 -1.04957339 -1.02020853
 -1.07893824 -1.37258681 -0.72655996 -0.81465453 -0.31545197 -0.84401939
 -1.37258681 -1.46068138 -1.07893824 -0.99084367]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X.iloc[:,1:] = ss.fit_transform(X.iloc[:,1:])

In [334]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=1)

In [335]:
tree = DecisionTreeClassifier(criterion='entropy',random_state=0)
tree.fit(X_train,y_train)
y_pred = tree.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_test,y_pred))

[[49 10]
 [ 9 32]]
              precision    recall  f1-score   support

           0       0.83      0.84      0.84        58
           1       0.78      0.76      0.77        42

    accuracy                           0.81       100
   macro avg       0.81      0.80      0.80       100
weighted avg       0.81      0.81      0.81       100

---
**without gender**

In [336]:
X = data.iloc[:,2:-1]
y = data.iloc[:,-1]
X

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [337]:
ss = StandardScaler()
X= ss.fit_transform(X)

In [338]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=1)

In [339]:
tree = DecisionTreeClassifier(criterion='entropy',random_state=0)
tree.fit(X_train,y_train)
y_pred = tree.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_test,y_pred))

[[48  7]
 [10 35]]
              precision    recall  f1-score   support

           0       0.87      0.83      0.85        58
           1       0.78      0.83      0.80        42

    accuracy                           0.83       100
   macro avg       0.83      0.83      0.83       100
weighted avg       0.83      0.83      0.83       100